"""
Interaction repository for tracking user-paper interactions.
Handles interaction history and filters.
UPDATED: Fixed JSONB handling for context field.
"""
from typing import List, Optional, Dict, Any
from datetime import datetime, timedelta
import asyncpg
import json  # ADDED: For JSONB serialization
from app.db.repositories.base import BaseRepository
from app.db.connection import DatabaseConnection
from app.utils.logger import get_logger

logger = get_logger(__name__)


class InteractionRepository(BaseRepository):
    """Repository for user interaction operations."""
    
    @property
    def table_name(self) -> str:
        return "user_interactions"
    
    def __init__(self, db: DatabaseConnection):
        super().__init__(db)
        logger.info("InteractionRepository initialized")
    
    async def create_interaction(
        self,
        user_id: int,
        paper_id: str,
        interaction_type: str,
        duration_seconds: Optional[int] = None,
        source: Optional[str] = None,
        position: Optional[int] = None,
        session_id: Optional[str] = None
    ) -> asyncpg.Record:
        """
        Record a user-paper interaction.
        NOTE: interaction_strength is GENERATED by database based on interaction_type.
        """
        logger.info(
            "Creating interaction",
            user_id=user_id,
            paper_id=paper_id,
            interaction_type=interaction_type
        )
        
        # Build context JSON object
        context = {}
        if source:
            context['source'] = source
        if position is not None:
            context['position'] = position
        if session_id:
            context['session_id'] = session_id
        
        # Serialize to JSON string for PostgreSQL JSONB column
        import json
        context_json = json.dumps(context) if context else None
        
        query = """
            INSERT INTO user_interactions (
                user_id, paper_id, interaction_type,
                duration_seconds, context
            )
            VALUES ($1, $2, $3, $4, $5::jsonb)
            RETURNING *
        """
        
        try:
            result = await self.db.fetchrow(
                query,
                user_id,
                paper_id,
                interaction_type,
                duration_seconds,
                context_json  # Pass JSON string
            )
            
            logger.info(
                "Interaction created",
                user_id=user_id,
                paper_id=paper_id,
                type=interaction_type,
                strength=result['interaction_strength']
            )
            
            return result
            
        except Exception as e:
            logger.error(
                "Interaction creation failed",
                user_id=user_id,
                paper_id=paper_id,
                error=str(e),
                exc_info=True
            )
            raise
    
    async def get_user_interactions(
        self,
        user_id: int,
        limit: Optional[int] = None,
        min_strength: Optional[float] = None,
        since: Optional[datetime] = None
    ) -> List[asyncpg.Record]:
        """
        Get user's interaction history.
        
        Args:
            user_id: User identifier
            limit: Maximum interactions to return
            min_strength: Minimum interaction strength
            since: Only interactions after this time
            
        Returns:
            List[Record]: Interaction records
        """
        logger.debug(
            "Getting user interactions",
            user_id=user_id,
            limit=limit,
            min_strength=min_strength
        )
        
        query = """
            SELECT ui.*, p.title, p.domain, p.year
            FROM user_interactions ui
            JOIN papers p ON ui.paper_id = p.paper_id
            WHERE ui.user_id = $1
        """
        
        params = [user_id]
        param_idx = 2
        
        if min_strength is not None:
            query += f" AND ui.interaction_strength >= ${param_idx}"
            params.append(min_strength)
            param_idx += 1
        
        if since:
            query += f" AND ui.created_at >= ${param_idx}"
            params.append(since)
            param_idx += 1
        
        query += " ORDER BY ui.created_at DESC"
        
        if limit:
            query += f" LIMIT ${param_idx}"
            params.append(limit)
        
        try:
            results = await self.db.fetch(query, *params)
            
            logger.debug(
                "Interactions retrieved",
                user_id=user_id,
                count=len(results)
            )
            
            return results
            
        except Exception as e:
            logger.error(
                "Interactions retrieval failed",
                user_id=user_id,
                error=str(e),
                exc_info=True
            )
            raise
    
    async def get_interaction_counts(
        self,
        user_id: int,
        days: int = 30
    ) -> Dict[str, int]:
        """
        Get counts of different interaction types.
        
        Args:
            user_id: User identifier
            days: Look back period in days
            
        Returns:
            Dict mapping interaction type to count
        """
        logger.debug(
            "Getting interaction counts",
            user_id=user_id,
            days=days
        )
        
        query = """
            SELECT 
                interaction_type,
                COUNT(*) as count
            FROM user_interactions
            WHERE user_id = $1
              AND created_at >= NOW() - INTERVAL '1 day' * $2
            GROUP BY interaction_type
        """
        
        try:
            results = await self.db.fetch(query, user_id, days)
            
            counts = {row['interaction_type']: row['count'] for row in results}
            
            logger.debug(
                "Interaction counts retrieved",
                user_id=user_id,
                counts=counts
            )
            
            return counts
            
        except Exception as e:
            logger.error(
                "Interaction counts retrieval failed",
                user_id=user_id,
                error=str(e),
                exc_info=True
            )
            raise
    
    async def get_meaningful_interactions_count(
        self,
        user_id: int
    ) -> int:
        """
        Count meaningful interactions (save, cite, download).
        Used for state transitions.
        
        Args:
            user_id: User identifier
            
        Returns:
            int: Count of meaningful interactions
        """
        logger.debug(
            "Counting meaningful interactions",
            user_id=user_id
        )
        
        query = """
            SELECT COUNT(*)
            FROM user_interactions
            WHERE user_id = $1
              AND interaction_type IN ('save', 'cite', 'download')
        """
        
        try:
            count = await self.db.fetchval(query, user_id)
            
            logger.debug(
                "Meaningful interactions counted",
                user_id=user_id,
                count=count
            )
            
            return count or 0
            
        except Exception as e:
            logger.error(
                "Meaningful interactions count failed",
                user_id=user_id,
                error=str(e),
                exc_info=True
            )
            raise
    
    async def get_domains_explored(self, user_id: int) -> int:
        """
        Count unique domains user has interacted with.
        
        Args:
            user_id: User identifier
            
        Returns:
            int: Number of unique domains
        """
        logger.debug("Counting domains explored", user_id=user_id)
        
        query = """
            SELECT COUNT(DISTINCT p.domain)
            FROM user_interactions ui
            JOIN papers p ON ui.paper_id = p.paper_id
            WHERE ui.user_id = $1
              AND ui.interaction_strength > 0
        """
        
        try:
            count = await self.db.fetchval(query, user_id)
            
            logger.debug(
                "Domains explored counted",
                user_id=user_id,
                count=count
            )
            
            return count or 0
            
        except Exception as e:
            logger.error(
                "Domains explored count failed",
                user_id=user_id,
                error=str(e),
                exc_info=True
            )
            raise
    
    async def add_paper_filter(
        self,
        user_id: int,
        paper_id: str,
        filter_type: str,
        reason: Optional[str] = None
    ) -> asyncpg.Record:
        """
        Add paper to user's filter list (don't show again).
        
        Args:
            user_id: User identifier
            paper_id: Paper to filter
            filter_type: 'not_interested', 'already_read', 'saved', 'dismissed'
            reason: Optional reason
            
        Returns:
            Record: Created filter record
        """
        logger.info(
            "Adding paper filter",
            user_id=user_id,
            paper_id=paper_id,
            filter_type=filter_type
        )
        
        query = """
            INSERT INTO user_paper_filters (
                user_id, paper_id, filter_type
            )
            VALUES ($1, $2, $3)
            ON CONFLICT (user_id, paper_id)
            DO UPDATE SET
                filter_type = EXCLUDED.filter_type
            RETURNING *
        """
        
        try:
            result = await self.db.fetchrow(
                query,
                user_id,
                paper_id,
                filter_type
            )
            
            logger.info(
                "Paper filter added",
                user_id=user_id,
                paper_id=paper_id
            )
            
            return result
            
        except Exception as e:
            logger.error(
                "Paper filter creation failed",
                user_id=user_id,
                paper_id=paper_id,
                error=str(e),
                exc_info=True
            )
            raise
    
    async def get_filtered_papers(
        self,
        user_id: int,
        filter_types: Optional[List[str]] = None
    ) -> List[str]:
        """
        Get list of paper IDs user has filtered.
        
        Args:
            user_id: User identifier
            filter_types: Optional filter types to include
            
        Returns:
            List[str]: Paper IDs
        """
        logger.debug(
            "Getting filtered papers",
            user_id=user_id,
            filter_types=filter_types
        )
        
        query = "SELECT paper_id FROM user_paper_filters WHERE user_id = $1"
        params = [user_id]
        
        if filter_types:
            query += " AND filter_type = ANY($2::text[])"
            params.append(filter_types)
        
        try:
            results = await self.db.fetch(query, *params)
            paper_ids = [row['paper_id'] for row in results]
            
            logger.debug(
                "Filtered papers retrieved",
                user_id=user_id,
                count=len(paper_ids)
            )
            
            return paper_ids
            
        except Exception as e:
            logger.error(
                "Filtered papers retrieval failed",
                user_id=user_id,
                error=str(e),
                exc_info=True
            )
            raise
    
    async def get_saved_papers(self, user_id: int) -> List[asyncpg.Record]:
        """
        Get papers user has saved.
        
        Args:
            user_id: User identifier
            
        Returns:
            List[Record]: Saved paper records
        """
        logger.debug("Getting saved papers", user_id=user_id)
        
        query = """
            SELECT 
                usp.*,
                p.title,
                p.authors,
                p.year,
                p.abstract,
                p.domain
            FROM user_saved_papers usp
            JOIN papers p ON usp.paper_id = p.paper_id
            WHERE usp.user_id = $1
            ORDER BY usp.saved_at DESC
        """
        
        try:
            results = await self.db.fetch(query, user_id)
            
            logger.debug(
                "Saved papers retrieved",
                user_id=user_id,
                count=len(results)
            )
            
            return results
            
        except Exception as e:
            logger.error(
                "Saved papers retrieval failed",
                user_id=user_id,
                error=str(e),
                exc_info=True
            )
            raise
# ============================================================================
    # Add these methods to app/db/repositories/interaction_repo.py
    # ============================================================================

    async def get_seen_paper_ids(
        self,
        user_id: int
    ) -> List[str]:
        """
        Get all paper IDs user has interacted with.
        
        Args:
            user_id: User identifier
            
        Returns:
            List of paper IDs
        """
        query = """
            SELECT DISTINCT paper_id
            FROM user_interactions
            WHERE user_id = $1
        """
        
        results = await self.db.fetch(query, user_id)
        return [r['paper_id'] for r in results]


    async def get_recommendation_history(
        self,
        user_id: int,
        limit: int = 10
    ) -> List[Dict]:
        """
        Get user's recommendation history.
        
        Args:
            user_id: User identifier
            limit: Number of events to return
            
        Returns:
            List of recommendation events
        """
        query = """
            SELECT 
                re.event_id,
                re.recommended_paper_ids,
                re.embedding_model,
                re.event_timestamp
            FROM recommendation_events re
            WHERE re.user_id = $1
            ORDER BY re.event_timestamp DESC
            LIMIT $2
        """
        
        results = await self.db.fetch(query, user_id, limit)
        return [dict(r) for r in results]

    async def check_embedding_update_trigger(
        self,
        user_id: int
    ) -> bool:
        """
        Check if user has enough new interactions to trigger embedding update.
        
        Args:
            user_id: User identifier
            
        Returns:
            bool: True if update should be triggered
        """
        logger.debug(
            "Checking embedding update trigger",
            user_id=user_id
        )
        
        # Get last embedding update time
        state_query = """
            SELECT last_embedding_update_minilm, last_embedding_update_specter
            FROM user_recommendation_state
            WHERE user_id = $1
        """
        
        state = await self.db.fetchrow(state_query, user_id)
        
        if not state:
            logger.debug("No state found, trigger update", user_id=user_id)
            return True
        
        # Use most recent update time
        last_update = max(
            state['last_embedding_update_minilm'] or datetime.min,
            state['last_embedding_update_specter'] or datetime.min
        )
        
        # Count interactions since last update
        count_query = """
            SELECT COUNT(*)
            FROM user_interactions
            WHERE user_id = $1
              AND created_at > $2
              AND interaction_type IN ('save', 'cite', 'download', 'like')
        """
        
        try:
            count = await self.db.fetchval(count_query, user_id, last_update)
            
            # Trigger if 5+ meaningful interactions
            should_trigger = count >= 5
            
            logger.debug(
                "Embedding update check complete",
                user_id=user_id,
                interactions_since_update=count,
                should_trigger=should_trigger
            )
            
            return should_trigger
            
        except Exception as e:
            logger.error(
                "Embedding update check failed",
                user_id=user_id,
                error=str(e),
                exc_info=True
            )
            raise